[workspace]
resolver = "2"
members = [
    "frontend",
    "server/api",
    "server/shuttle", "server/standalone",
]

[profile.release]
strip = true

[workspace.dependencies]
api = { version = "0.1.0", path = "./server/api"}
