[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { workspace = true }
shuttle-runtime = { version = "0.36.0", default-features = false }
shuttle-axum = "0.36.0"
