name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-gnu       , use-cross: false , extension: ""   }
          - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl      , use-cross: true  , extension: ""   }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-gnueabihf  , use-cross: true  , extension: ""   }
          - { os: ubuntu-latest  , target: armv7-unknown-linux-musleabihf , use-cross: true  , extension: ""   }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-gnu      , use-cross: true  , extension: ""   }
          - { os: ubuntu-latest  , target: aarch64-unknown-linux-musl     , use-cross: true  , extension: ""   }
          - { os: macos-latest   , target: x86_64-apple-darwin            , use-cross: false , extension: ""   }
          - { os: macos-latest   , target: aarch64-apple-darwin           , use-cross: false , extension: ""   }
          - { os: windows-latest , target: x86_64-pc-windows-msvc         , use-cross: false , extension: .exe }
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses:  dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.job.target }},wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Trunk
        run: cargo binstall -y trunk

      - name: Build frontend
        run: |
          pushd frontend
          CARGO_TARGET_DIR=../target-trunk trunk build --release --public-url /
          popd

      - name: Build backend
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          command: build
          args: --bin backend --release --target ${{ matrix.job.target }}
          use-cross: ${{ matrix.job.use-cross }}
          cross-version: 0.2.5

      - name: Compress
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: .
          files: |
            dist/
            target/${{ matrix.job.target }}/release/backend${{ matrix.job.extension }}
          outPath: ${{ matrix.job.target }}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ matrix.job.target }}.tar.gz
