name: Shuttle Deploy

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses:  dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Trunk
        run: cargo binstall -y trunk

      - name: Install TailwindCSS
        run: |
          wget -q https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O tailwindcss
          chmod +x tailwindcss
          mv tailwindcss /usr/local/bin/

      - name: Build frontend
        run: |
          pushd frontend
          trunk build --release -d ../shuttle-dist/
          popd

      - name: Shuttle Deploy
        uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          allow-dirty: "true"
